### PR TITLE
Workstation region assignments

### LINKED ISSUE #888: workstations:session-create post fails when the container image is not ready
See https://sentry.io/organizations/grand-challenge/issues/1163103558/?project=303639&query=is%3Aunresolved&statsPeriod=14d

### LINKED ISSUE #1382: Workstation Session create view always uses default region
Add a check on `Session.save()` if adding and region is None to set the region to one that is in use (or closest to the user).

### PR DESCRIPTION
**Pull request by jmsmkn**
This PR:

- Removes the workstation session redirect view, instead uses the create view which is doing a get or create for a running session for that user in the requested region
- Adds region assignment to the create view
- Adds a ping endpoint with CORS for the main domain to nginx
- Automatically determine the region

This PR does not let you override the region, but on failure will launch in the default region. Overrides can follow later if needed (I will use a vpn for now).

Fixes #888 
Closes #1382

### CODE REVIEW

File: app/grandchallenge/workstations/static/workstations/js/session-region.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    session_modal.modal({show: true});
+
+    const ping_endpoint = JSON.parse(document.getElementById("ping-endpoint-data").textContent);
+    const region_selection = document.getElementById("id_region");
+    const urls = [...region_selection.options].map(function (o) {
+        return `https://${o.value}.${ping_endpoint}`
+    });
+
+    Promise.race(
+        urls.map(
```
Comment (HarmvZ) [inline app/grandchallenge/workstations/static/workstations/js/session-region.js:17]: This map could be combined with the `map()` on line 12

File: app/grandchallenge/workstations/static/workstations/js/session-region.js [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+                )
+                .catch(
+                    // Nothing resolved
+                    error => console.log(error)
+                )
+        )
+    )
+        .then(
+            response => {
+                if (response !== undefined) {
```
Comment (HarmvZ) [inline app/grandchallenge/workstations/static/workstations/js/session-region.js:32]: Unfortunately it is still better to use `typeof response !== 'undefined'` to support <ES2015 browsers.

File: app/grandchallenge/workstations/static/workstations/js/session-region.js [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+                    // If we have a match, find out what server this is for
+                    let regexp = /^https:\/\/([\w-]+).*/;
+                    let m = response.url.match(regexp);
+
+                    if (m !== undefined) {
```
Comment (HarmvZ) [inline app/grandchallenge/workstations/static/workstations/js/session-region.js:37]: `typeof m !== 'undefined'`

File: app/grandchallenge/workstations/static/workstations/js/session-region.js [hunk 4]
```diff
@@ -0,0 +1,46 @@
+function setModalLoadingMessage(msg) {
+    document.getElementById("sessionStateMsg").innerHTML = msg;
```
Comment (HarmvZ) [inline app/grandchallenge/workstations/static/workstations/js/session-region.js:2]: It is generally better to avoid `innerHTML` to prevent XSS attacks unless you explicitly want to add child elements by text. An XSS attack is not possible here, but still, it is good practice to use `textContent` or `innnerText` here since you are only setting text.

File: app/grandchallenge/workstations/static/workstations/js/session-region.js [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+                    error => console.log(error)
+                )
+        )
+    )
+        .then(
+            response => {
+                if (response !== undefined) {
+                    // If we have a match, find out what server this is for
+                    let regexp = /^https:\/\/([\w-]+).*/;
+                    let m = response.url.match(regexp);
```
Comment (HarmvZ) [inline app/grandchallenge/workstations/static/workstations/js/session-region.js:35]: Can be `const`.

(This comment dit not get submitted during the review somehow)
